-- SQL script that creates a function SafeDiv
DROP FUNCTION IF EXISTS safeDiv;

DELIMITER $$
CREATE FUNCTION safeDiv(a INT, b INT)
RETURNS FLOAT DETERMINISTIC
BEGIN
	IF b = 0 THEN
		RETURN 0;
	ELSE
		RETURN a / b;
	END IF;
END$$
DELIMITER ;
